"""add token_count to source

Revision ID: caeecb4cdaeb
Revises: 4e1b8f72c9a1
Create Date: 2025-11-22 14:45:33.341201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caeecb4cdaeb'
down_revision: Union[str, None] = '4e1b8f72c9a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('token_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'token_count')
    # ### end Alembic commands ###
